add news search with filters to NewsService, previous methods were de…
fmh-charity/fmh-backend pull request #131
Opened 2022-11-10 09:29 UTC by Shinjitsu0

…leted

2022-11-13 07:32 UTC, Pro100proff requested changes

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/Util.java
> +            Date simpleDate = new SimpleDateFormat("dd.MM.yyyy").parse(date);
вместо SimpleDateFormat использовать DatetimeFormatter
С помощью DatetimeFormatter.parse получаем LocalDate и приводим к Instant

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> -            @ApiParam (required = false, name = "pages", value = "От 0")
На будущее, старайся форматировать плиз только то что исправлял, засоряется ревью лишними правками

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> +            @ApiParam(required = false, name = "newsCategoryId", value = "Сортировка по новостной категории")
Фильтрация по категории

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> +            @RequestParam(required = false) String publishDateFrom,
Мы же можем сразу принимать LocalDate вместо String, он нормально сериализуется

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    @Query(value = "SELECT n FROM News n WHERE n.publishDate <= :currentDate "
Молодец, хороший запрос! Будет время проверь его стоимость с помощью explain в postgres, стоимость запроса не должна превышать 100-200

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    Page<News> findAllWithFiltersWherePublishDateLessThanCurrentAndDeletedIsFalseAndPublishEnabledIsTrue(
переименуй пожалуйста в более понятное название метода, тут оно слишком длинное, например getActualNewsInInterval

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    Page<News> findAllWithFiltersWhereDeletedIsFalse(
getAllNewsInInterval например

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        NewsCategory newsCategory = newsCategoryId == null ? null : newsCategoryRepository.findNewsCategoryById(newsCategoryId);
Попробуй лучше Optional.offNullable().orElse(null)

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        Instant instantValuePublishDateFrom = publishDateFrom == null ? null : util.getInstantFromString(publishDateFrom);
Попробуй лучше Optional.offNullable().orElse(null)

2022-11-13 07:32 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        Instant instantValuePublishDateTo = publishDateTo == null ? null : util.getInstantFromString(publishDateTo);
Попробуй лучше Optional.offNullable().orElse(null)

2022-11-13 10:13 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    @Query(value = "SELECT n FROM News n WHERE n.publishDate <= :currentDate "
Seq Scan on news n  (cost=0.00..16.60 rows=660 width=118)

2022-11-13 10:25 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/Util.java
> +            Date simpleDate = new SimpleDateFormat("dd.MM.yyyy").parse(date);
Исправил параметр метода на LocalDate и привел его к Instant

2022-11-13 10:25 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> -            @ApiParam (required = false, name = "pages", value = "От 0")
Понял, постараюсь.

2022-11-13 10:25 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> +            @ApiParam(required = false, name = "newsCategoryId", value = "Сортировка по новостной категории")
Исправил

2022-11-13 10:25 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/controller/NewsController.java
> +            @RequestParam(required = false) String publishDateFrom,
Не знал, спасибо за информацию)

2022-11-13 10:26 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    Page<News> findAllWithFiltersWherePublishDateLessThanCurrentAndDeletedIsFalseAndPublishEnabledIsTrue(
Исправил на getActualNewsInInterval

2022-11-13 10:26 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dao/repository/NewsRepository.java
> +    Page<News> findAllWithFiltersWhereDeletedIsFalse(
Исправил на getAllNewsInInterval

2022-11-13 10:28 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        NewsCategory newsCategory = newsCategoryId == null ? null : newsCategoryRepository.findNewsCategoryById(newsCategoryId);
Не уверен в правильности но заменил

2022-11-14 10:45 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        Instant instantValuePublishDateFrom = publishDateFrom == null ? null : util.getInstantFromString(publishDateFrom);
Готово

2022-11-14 10:45 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/news/NewsServiceImpl.java
> +        Instant instantValuePublishDateTo = publishDateTo == null ? null : util.getInstantFromString(publishDateTo);
Готово

2022-11-15 18:35 UTC, Shinjitsu0 commented
https://trello.com/c/KfwvxBeY/13-добавить-фильтрацию-новостей
https://trello.com/c/5XkyMgCl/11-невозможно-удалить-новость

2022-11-16 16:50 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/Util.java
> +        return localDate.atStartOfDay(ZoneId.systemDefault()).toInstant();
у нас не всегда должно быть atStartOfDay, например с новостями, для publishDateTo должно быть atEndOfDay

2022-11-16 17:20 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/Util.java
> +        return localDate.atStartOfDay(ZoneId.systemDefault()).toInstant();
Добавил новый метод в Util возвращающий время на конец дня.

2022-11-16 17:27 UTC, Pro100proff approved these changes

2022-11-16 17:33 UTC, merged