- chek login and password when login
fmh-charity/fmh-backend pull request #18
Opened 2021-12-09 18:23 UTC by AnastasiyaShark

- fix refreshToken
- create RefreshTokenRequest.java

2021-12-09 19:11 UTC, neee commented on src/main/java/ru/iteco/fmh/service/AuthService.java
> +        System.out.println(refreshToken);
Лучше удалить такое

2021-12-09 19:13 UTC, neee commented on src/main/java/ru/iteco/fmh/security/JwtProvider.java
> +                .setExpiration(Timestamp.from(Instant.now().plus(20, ChronoUnit.MINUTES)))
почему минуты стали?

2021-12-09 19:13 UTC, neee requested changes

2021-12-09 19:13 UTC, neee commented on src/main/java/ru/iteco/fmh/security/JwtProvider.java
> +                .setExpiration(Timestamp.from(Instant.now().plus(5, ChronoUnit.MINUTES)))
был 1 день, давай вернем

2021-12-09 20:55 UTC, AnastasiyaShark commented on src/main/java/ru/iteco/fmh/service/AuthService.java
> +        System.out.println(refreshToken);
забыла

2021-12-09 20:57 UTC, AnastasiyaShark commented on src/main/java/ru/iteco/fmh/security/JwtProvider.java
> +                .setExpiration(Timestamp.from(Instant.now().plus(20, ChronoUnit.MINUTES)))
я сказала уже: Android временно попросил поменять для тестирования. Потом вернём

2021-12-09 20:57 UTC, AnastasiyaShark commented on src/main/java/ru/iteco/fmh/security/JwtProvider.java
> +                .setExpiration(Timestamp.from(Instant.now().plus(5, ChronoUnit.MINUTES)))
тоже самое

2021-12-10 06:31 UTC, neee commented on src/main/java/ru/iteco/fmh/security/JwtProvider.java
> +                .setExpiration(Timestamp.from(Instant.now().plus(20, ChronoUnit.MINUTES)))
Ок

2021-12-10 14:40 UTC, AnastasiyaShark commented on src/main/java/ru/iteco/fmh/service/AuthService.java
> +        if (!user.getPassword().equals(loginRequest.getPassword())) {
+

2021-12-10 14:53 UTC, neee approved these changes

2021-12-10 14:54 UTC, merged