fmh_back 69 Создание метода подтверждения роли пользователя
fmh-charity/fmh-backend pull request #237
Opened 2023-04-10 16:23 UTC by 0202-D

https://trello.com/c/b06i36DV/69-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%BF%D0%BE%D0%B4%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F

2023-04-12 18:04 UTC, Pro100proff requested changes

2023-04-12 18:04 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/user/UserRoleClaim.java
> +    @ManyToOne()
лишние скобки

2023-04-12 18:04 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +        var role = roleRepository.findById(claimDto.getRoleId())
поиск через репозитори надо вынести в сервисный метод. В конвертере просто перенос полей

2023-04-13 15:58 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        if (userRoleClaim.isEmpty()) {
Спасибо,  сделано

2023-04-13 15:58 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/user/UserRoleClaim.java
> +    @ManyToOne()
убрал

2023-04-13 15:58 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +        var role = roleRepository.findById(claimDto.getRoleId())
готово

2023-04-15 19:32 UTC, Pro100proff approved these changes

2023-04-15 19:37 UTC, merged