fmh_back71 Добавить метод получения информации о пользователе для админа
fmh-charity/fmh-backend pull request #238
Opened 2023-04-12 06:03 UTC by EvgeniySiganov

В контроллере ru.iteco.fmh.controller.UsersController добавить GET /{userId}

Метод доступен для роли админ

Создать новое дто UserInfoDto с полями:

id: Integer
firstName:String
lastName:String
middleName:String
isAdmin:Boolean
email:`UserEmailDto`
roles:List<String>
isConfirmed:boolean
userRoleClaim: UserRoleClaimDto
Создать дто UserRoleClaimDto:

id:Integer
role:String
status:RoleClaimStatus
createdAt: Instant
Создать конвертер UserToUserInfoDto, на вход получающий User и возвращающий сущность UserInfoDto. Важно! У пользователя может не быть UserRoleClaim. В этом случае проставляем isConfirmed = true, userRoleClaim = null

Создать новый метод в ru.iteco.fmh.service.user.UserService getUserInfo:

Ищем пользователя по id
Если не нашли то NotFoundException
возвращаем информацию о найденном пользователе через созданный конвертер

2023-04-15 19:29 UTC, Pro100proff requested changes

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimToUserRoleClaimDtoConverter.java
> +        UserRoleClaimDto userRoleClaimDto = new UserRoleClaimDto();
лучше через builder это все делать

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserInfoDtoConverter.java
> +    UserRoleClaimRepository userRoleClaimRepository;
userRoleClaimRepository и userRoleClaimToUserRoleClaimDtoConverter не используется

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserInfoDtoConverter.java
> +public class UserToUserInfoDtoConverter implements Converter<User, UserInfoDto> {
в МР https://github.com/fmh-charity/fmh-backend/pull/239 добавляется профиль пользователя, надо будет после влития той ветки поправить конвертер

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserInfoDtoConverter.java
> +        userInfoDto.setAdmin(roles.stream().anyMatch(n -> n.getName().equals("ROLE_ADMINISTRATOR")));
здесь использовать утильный метод isAdmin()

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            userRoleClaimDto = conversionService.convert(userRoleClaim, UserRoleClaimDto.class);
место 62 строки, только здесь создавать переменную UserRoleClaimDto

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            assert userRoleClaimDto != null;
ассерт убрать

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        UserRoleClaim userRoleClaim = userRoleClaimRepository.findUserRoleClaimByUserId(id);
здесь ищем не просто все заявки а в статусах REJECTED и NEW. Для этого надо создать новый метод репозитори который находит первую заявку findFirstby...

2023-04-15 19:29 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            userInfoDto.setUserRoleClaim(userRoleClaimDto);
не хватает userInfoDto.setConfirmed(false);

2023-04-16 08:36 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserInfoDtoConverter.java
> +public class UserToUserInfoDtoConverter implements Converter<User, UserInfoDto> {
ок, жду влития

2023-04-20 16:19 UTC, Pro100proff requested changes

2023-04-20 16:19 UTC, Pro100proff commented on cucumber-tests/pom.xml
> +        <!--<dependency>
лишний депенденси появился

2023-04-20 16:19 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        UserRoleClaimDto userRoleClaimDto;
лишнее объявление,можно сразу сделать на строке UserRoleClaimDto userRoleClaimDto =  conversionService.convert(userRoleClaim, UserRoleClaimDto.class);

2023-04-20 16:19 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            userRoleClaimDto.setRole(userRoleClaim.getRole().getName());
вынести в конвертер UserRoleClaimToUserRoleClaimDtoConverter

2023-04-23 09:33 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserInfoDtoConverter.java
> +public class UserToUserInfoDtoConverter implements Converter<User, UserInfoDto> {
поправил

2023-04-23 09:34 UTC, EvgeniySiganov commented on cucumber-tests/pom.xml
> +        <!--<dependency>
удалил

2023-04-23 09:34 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        UserRoleClaimDto userRoleClaimDto;
сделал

2023-04-23 09:34 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            userRoleClaimDto.setRole(userRoleClaim.getRole().getName());
вынес

2023-04-27 16:44 UTC, Pro100proff requested changes

2023-04-27 16:44 UTC, Pro100proff commented on backend/src/main/resources/application-dev.yml
> +    show-sql: true
вернуть обратно в false

2023-04-27 16:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +    private final RoleRepository roleRepository;
репозитори в конвертере не используем

2023-04-27 16:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +        Role role = roleRepository.findRoleById(claimDto.getRoleId());
роль должна проставляться в сервисе

2023-04-27 16:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
>  public class UserRoleClaimShortToUserRoleClaim implements Converter<UserRoleClaimShort, UserRoleClaim> {
этот конвертер как то твою задачу трогает?

2023-04-28 04:01 UTC, EvgeniySiganov commented on backend/src/main/resources/application-dev.yml
> +    show-sql: true
вернул

2023-04-28 04:01 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +    private final RoleRepository roleRepository;
удалил

2023-04-28 04:01 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
> +        Role role = roleRepository.findRoleById(claimDto.getRoleId());
удалил

2023-04-28 04:02 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserRoleClaimShortToUserRoleClaim.java
>  public class UserRoleClaimShortToUserRoleClaim implements Converter<UserRoleClaimShort, UserRoleClaim> {
падал тест на нём у меня на локальном компе, и здесь на проверке не проходил коммит

2023-04-29 09:19 UTC, Pro100proff approved these changes

2023-04-29 09:46 UTC, merged