fmh_back68 Создание профиля пользователя
fmh-charity/fmh-backend pull request #239
Opened 2023-04-15 14:09 UTC by Shinjitsu0

2023-04-15 19:10 UTC, Pro100proff requested changes

2023-04-15 19:10 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/AuthService.java
> +        final String availableRole = "ROLE_VOLUNTEER";
надо вынести в статическую переменную List<String> availableToApplyRoles

2023-04-15 19:10 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/AuthService.java
> +        return roleRepository.findAllByDeletedIsFalse().stream().filter(role -> role.getName().equals(availableRole))
делаем поиск не по всем ролям, а только по тем которые доступны для подтверждения админом и убираем фильтр

2023-04-15 19:10 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserDtoConverter.java
> +        return UserDto.builder().id(user.getId()).login(user.getLogin()).password(user.getPassword()).profile(userProfileDtoRs).build();
password не нужно отправлять

2023-04-15 19:10 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserShortInfoDtoConverter.java
>          boolean isAdmin = userRoles.stream().anyMatch(n -> (n.getName().equals(administrator)));
вместо isAdmin надо использовать утильный метод isAdmin()

2023-04-15 19:10 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +import ru.iteco.fmh.dto.user.UserDto;
где это дто здесь используется?

2023-04-16 08:40 UTC, Shinjitsu0 commented on backend/src/main/resources/db/migration/dev/V21__create_tbl_profile_and_alter_tbl_users.sql
> +insert into profile(first_name, last_name, middle_name, email, deleted, date_of_birth, email_confirmed)
Исправил

2023-04-16 08:41 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/AuthService.java
> +        Optional<User> foundedUserByProfileEmail = userRepository.findUserByProfileEmail(registrationRequest.getEmail());
Добавил репозиторий для поиска профиля

2023-04-16 08:41 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/AuthService.java
> +        final String availableRole = "ROLE_VOLUNTEER";
Вынес переменную

2023-04-16 08:42 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/AuthService.java
> +        return roleRepository.findAllByDeletedIsFalse().stream().filter(role -> role.getName().equals(availableRole))
Переделал, надеюсь правильно понял.

2023-04-16 08:56 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserDtoConverter.java
> +        return UserDto.builder().id(user.getId()).login(user.getLogin()).password(user.getPassword()).profile(userProfileDtoRs).build();
Убрал

2023-04-16 08:56 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/converter/user/UserToUserShortInfoDtoConverter.java
>          boolean isAdmin = userRoles.stream().anyMatch(n -> (n.getName().equals(administrator)));
Переделал

2023-04-16 08:57 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +import ru.iteco.fmh.dto.user.UserDto;
Это я метод для тестирования добавлял, метод удалил а импорт забыл

2023-04-16 10:11 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dto/user/UserDto.java
>      String password;
пароль убери плиз

2023-04-16 10:11 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dto/user/UserDto.java
> +    ProfileDtoRs profile;
лучше оставить как было, так как аналитика и фронт уже разработаны под предыдущее дто

2023-04-16 10:11 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/UserRepository.java
> +import org.springframework.data.jpa.repository.Query;
лишние импорты появились

2023-04-16 15:38 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dto/user/UserDto.java
>      String password;
Убрал

2023-04-16 15:40 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dto/user/UserDto.java
> +    ProfileDtoRs profile;
Оставил как было, только убрал поля String password, String phoneNumber и поле String shortUserName оно непонятно для чего нужно и нигде не заполнялось.

2023-04-16 15:40 UTC, Shinjitsu0 commented on backend/src/main/java/ru/iteco/fmh/dao/repository/UserRepository.java
> +import org.springframework.data.jpa.repository.Query;
Убрал

2023-04-20 16:04 UTC, Pro100proff approved these changes

2023-04-20 16:05 UTC, merged