fmh_back 70 Поправить метод вывода списка пользователей
fmh-charity/fmh-backend pull request #240
Opened 2023-04-20 15:53 UTC by 0202-D

https://trello.com/c/kPykHGLJ/70-%D0%BF%D0%BE%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D0%B0-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9

2023-04-27 17:22 UTC, Pro100proff requested changes

2023-04-27 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        user.setUserRoleClaim(entity);
это лишнее, достаточно засетить в одном месте

2023-04-27 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        List<User> list;
старайся избегать таких объявлений без инициализаций

2023-04-27 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAll(pageRequest).getContent();
сразу делай return userRepository.findAll(pageRequest).getContent().map(conversion).toList

2023-04-27 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAllByRoleClaimIsConfirmedOrNull(pageRequest);
здесь аналогично return

2023-04-27 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAllByRoleClaimIsNewOrRejected(pageRequest);
здесь аналогично return

2023-04-28 16:22 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/dao/repository/UserRepository.java
> +    @Query(value = "SELECT  w from User w inner join w.userRoleClaim wr where wr.status='CONFIRMED'or wr.status='null'")
готово

2023-04-28 16:22 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        user.setUserRoleClaim(entity);
ок

2023-04-28 16:23 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        List<User> list;
Понял , спасибо

2023-04-28 16:23 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            if (i.getUserRoleClaim() == null || i.getUserRoleClaim().getStatus() == CONFIRMED) {
вынес

2023-04-28 16:23 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAll(pageRequest).getContent();
готово

2023-04-28 16:23 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAllByRoleClaimIsConfirmedOrNull(pageRequest);
ок

2023-04-28 16:26 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            list = userRepository.findAllByRoleClaimIsNewOrRejected(pageRequest);
ок

2023-04-29 09:16 UTC, Pro100proff requested changes

2023-04-29 09:16 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/UserRepository.java
> +    @Query(value = "SELECT  w from User w left join w.userRoleClaim wr where wr.status='CONFIRMED'or wr.status='null'")
локально проверь работоспособность запроса для пользователей без заявок. Есть подозрение что упадет по nullpointer

2023-04-29 09:16 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        var user = userRepository.findById(claimDto.getUserId())
В claimDto надо заменить поле userId на User. В методе ru.iteco.fmh.service.AuthService.createRolesClaim уже может передаваться сущность юзера, поэтому его нет смысла заново вытаскивать из бд

2023-04-29 09:16 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        var user = userRepository.findById(claimDto.getUserId())
здесь аналогично create, сразу принимать сущность User из метода ru.iteco.fmh.service.AuthService.createRolesClaim

2023-04-29 15:54 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/dao/repository/UserRepository.java
> +    @Query(value = "SELECT  w from User w left join w.userRoleClaim wr where wr.status='CONFIRMED'or wr.status='null'")
разные варианты проверял , в том с полностью пустой таблицей заявок , nullpoiner не ловил

2023-04-29 15:54 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        var user = userRepository.findById(claimDto.getUserId())
готово

2023-04-29 15:54 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserRoleClaimServiceImpl.java
> +        var user = userRepository.findById(claimDto.getUserId())
готово

2023-05-04 16:51 UTC, merged