fmh_back 73 Создать сущность Сотрудник
fmh-charity/fmh-backend pull request #241
Opened 2023-04-24 16:19 UTC by 0202-D

https://trello.com/c/e1KrkqyW/73-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA

2023-04-29 09:44 UTC, Pro100proff requested changes

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/resources/db/migration/dev/V22__create_tables_employees_schedule_positions.sql
> +create table if not exists schedule
добавь еще плиз поле номер недели week int, в задаче забыл дописать

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/resources/db/migration/dev/V22__create_tables_employees_schedule_positions.sql
> +create index employee_month_year_index
добавь еще плиз индекс на новое поле недели + год

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +@ToString
не надо его везде ставить, может зааффектить сериализацию класса в хибере

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Month.java
> +public enum Month {
это лишнее, в джаве уже есть стандартный енум Month

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Schedule.java
> +    Month month;
джавовский енум используем

2023-04-29 09:44 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Schedule.java
> +public class Schedule {
неделю не забудь сюда добавить

2023-04-29 16:19 UTC, 0202-D commented on backend/src/main/resources/db/migration/dev/V22__create_tables_employees_schedule_positions.sql
> +create table if not exists schedule
добавил

2023-04-29 16:19 UTC, 0202-D commented on backend/src/main/resources/db/migration/dev/V22__create_tables_employees_schedule_positions.sql
> +create index employee_month_year_index
сделано

2023-04-29 16:20 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +@ToString
убрал

2023-04-29 16:20 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/employee/Month.java
> +public enum Month {
спасибо, убрал

2023-04-29 16:20 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/employee/Schedule.java
> +    Month month;
ок

2023-04-29 16:20 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/employee/Schedule.java
> +public class Schedule {
не забыл

2023-05-04 16:56 UTC, Pro100proff requested changes
оправить индекс для года и недели

2023-05-04 17:11 UTC, 0202-D commented on backend/src/main/resources/db/migration/dev/V22__create_tables_employees_schedule_positions.sql
> +create index employee_month_year_index
поправил

2023-05-06 10:36 UTC, Pro100proff approved these changes

2023-05-06 10:36 UTC, merged