fmh_back72 1. Добавить колонку profile_id, 2. Добавить скрипт поиска …
fmh-charity/fmh-backend pull request #242
Opened 2023-04-30 10:47 UTC by EvgeniySiganov

…профиля по перс данным пользователя и заполнить новую колонку profile_id, 3. Колонки с перс информацией удалить: firstname, lastname, middlename, birthdate, 4. Поправить сущность Patient в соответствии с таблицей бд - убрать лишние поля и заджойнить поле profile:Profile, 5. Поправить соответствующие конвертеры, 6. В методе ru.iteco.fmh.service.patient.PatientServiceImpl#updatePatient поправить заполнение полей профиля

2023-05-04 17:33 UTC, Pro100proff requested changes

2023-05-04 17:33 UTC, Pro100proff commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +select id, first_name, last_name, middle_name, deleted, birth_date
Надо чуть чуть переделать, так как в таблице профилей уже есть инфа из таблицы users. Поэтому:
1. Убрать id из запроса
2. В выборке должны попасть только те записи, которых нет в таблице profile.
   select p.first_name, p.last_name, p.middle_name, p.deleted, p.birth_date from patient p, profile pf where p.firstname != pf.firstname and p.lastname != pf.lastname and p.middle_name != pf.middle_name and p.birth_date != pf.birth_date

2023-05-04 17:33 UTC, Pro100proff commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +alter table patient
колонки пока не удаляем

2023-05-04 17:33 UTC, Pro100proff commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +update patient set profile_id = (select id from profile where patient.id = profile.id)
а вот здесь уже наоборот ищем совпадающие колонки в таблице профиля по фио + др

2023-05-04 17:33 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/user/Profile.java
> +@SQLDelete(sql = "UPDATE profile SET deleted = true WHERE id=?")
это на случай delete так отрабатывать будет?

2023-05-04 17:33 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/Patient.java
> -    @Pattern(regexp = "^[а-яА-ЯёЁa-zA-Z]+$")
Проверки NotBlank и Pattern добавь плиз в профиль

2023-05-05 03:50 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/model/user/Profile.java
> +@SQLDelete(sql = "UPDATE profile SET deleted = true WHERE id=?")
я это прописал из-за проблем с тестами, после этого проблемы ушли

2023-05-05 04:04 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/model/user/Profile.java
> +@SQLDelete(sql = "UPDATE profile SET deleted = true WHERE id=?")
> это на случай delete так отрабатывать будет?

мягкое удаление выставлением флага deleted = true

2023-05-05 04:41 UTC, EvgeniySiganov commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +select id, first_name, last_name, middle_name, deleted, birth_date
поправил

2023-05-05 04:41 UTC, EvgeniySiganov commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +alter table patient
не удалил колонки

2023-05-05 04:42 UTC, EvgeniySiganov commented on backend/src/main/resources/db/migration/dev/V22__alter_tbl_patient.sql
> +update patient set profile_id = (select id from profile where patient.id = profile.id)
нашёл

2023-05-05 04:42 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/model/Patient.java
> -    @Pattern(regexp = "^[а-яА-ЯёЁa-zA-Z]+$")
добавил

2023-05-06 10:35 UTC, Pro100proff approved these changes

2023-05-06 10:35 UTC, merged