Feature/fmh back74 Метод создания сотрудника
fmh-charity/fmh-backend pull request #250
Opened 2023-05-14 09:29 UTC by 0202-D

https://trello.com/c/tjQcCm03/74-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA%D0%B0

2023-05-20 13:15 UTC, Pro100proff requested changes

2023-05-20 13:15 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var role = roleRepository.findRoleByName("ROLE_MEDICAL_WORKER").get();
имя роли ROLE_MEDICAL_WORKER нужно вынести в утильный класс с переменной. Просто get вызывать опасно, так как всегда появляется шанс словить nullpointer. В данном случае лучше добавить orElseThrow(() -> new IllegalArgumentException("Не найдена роль мед сотрудника")

2023-05-20 13:15 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                .description(request.getDescription()).scheduleType(request.getScheduleType()).active(false)
active = true

2023-05-20 13:15 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var employee = Employee.builder().profile(profile).position(position)
Билдер в куче делать не надо. Каждый вызов цепочки на отдельно строке

2023-05-20 19:29 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/config/OpenApiConfiguration.java
> +    static {
Поправил. Без этой конфигурации LocalTime выглядел в swagger как обьект и приложение падало с ошибкой : 
Cannot deserialize value of type `java.time.LocalTime` from Object value (token `JsonToken.START_OBJECT`)

2023-05-20 19:30 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var role = roleRepository.findRoleByName("ROLE_MEDICAL_WORKER").get();
Вынес, и добавил обработку возможной ошибки

2023-05-20 19:30 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var employee = Employee.builder().profile(profile).position(position)
Поправил

2023-05-21 17:26 UTC, Pro100proff requested changes

2023-05-21 17:26 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/config/OpenApiConfiguration.java
> +    public void configureLocalTimeSchema() {
этот конфиг нельзя добавить в customOpenApi?

2023-05-21 17:26 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var user = User.builder().login(request.getEmail())
здесь тоже перенеси .login(request.getEmail()) на след строку

2023-05-21 17:26 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var profile = Profile.builder().firstName(request.getFirstName()).lastName(request.getLastName())
здесь тоже разбей на разные строки

2023-05-21 17:26 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        return EmployeeRegistrationResponse.builder()
здесь лучше конвертер сделать из Employee в EmployeeRegistrationResponse, слишком большой билдер. Дополнительно надо будет добавить в сущность Profile ссылку на поле User

2023-05-21 17:26 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        String content = "Вы успешно зарегестрированы в приложени Вхосписе. Ваш логин : "
вынеси в приватный метод отправку email с аргументами User, password

2023-05-22 17:59 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var user = User.builder().login(request.getEmail())
перенес

2023-05-22 17:59 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        var profile = Profile.builder().firstName(request.getFirstName()).lastName(request.getLastName())
сделано

2023-05-22 18:00 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        String content = "Вы успешно зарегестрированы в приложени Вхосписе. Ваш логин : "
вынес

2023-05-28 09:35 UTC, Pro100proff approved these changes

2023-05-28 09:35 UTC, merged