fmh_back72 Create method for changing profile cards by userId
fmh-charity/fmh-backend pull request #251
Opened 2023-05-17 02:22 UTC by EvgeniySiganov

Необходимо создать метод для изменения карточки профиля пользователя по его userId

https://pmhproject.myjetbrains.com/youtrack/articles/pmh-A-14/09-Upravlenie-polzovatelyami#2.4-redaktirovanie-kartochki-polzovatelya

В контроллере ru.iteco.fmh.controller.UsersController создать эндпойнт PUT /{userId}.

Метод доступен только администратору

На вход приходит дто ProfileChangingRequest:

firstName:String,

lastName:String,

middleName:String,

dateOfBirth:LocalDate,

email:String,

roleIds:Set<Int>

На каждое из полей добавить проверку что оно не пустое

В ответ возвращаем ru.iteco.fmh.dto.user.UserShortInfoDto

В сервисе ru.iteco.fmh.service.user.UserService создать метод updateUser(userId, ProfileChangingRequest):

находит User по его id

Изменяет роль согласно roleIds

Изменяет поля в профиле

сохраняет User

возвращает UserShortInfoDto

2023-05-17 15:37 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
Учусь делать review и комментить, если Вы не против) 
А что , если нет user с таким id ?

2023-05-18 03:44 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
Конечно, исправил, теперь бросаю исключение "Пользователь не найден"

2023-05-18 03:55 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
Можно в одну строчку с orElseThrow()

2023-05-20 13:19 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
Добавлю, вместо метода findUserById нужно использовать findById встроенный + как написал Дима выше сразу добавить orElseThrow

2023-05-20 13:22 UTC, Pro100proff requested changes

2023-05-20 13:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        profile.setEmail(profileChangingRequest.getEmail());
с email надо аккуратнее. Вначале проверить что он отличается от существующего. Если отличается то проставить новый + признак emailConfirmed = false. Далее отправить ссылку на подтверждения email

2023-05-21 07:26 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
поменял реализацию

2023-05-21 07:27 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        profile.setEmail(profileChangingRequest.getEmail());
Поменял реализацию. Проверял, на почту приходит как и обычное подтвержение так и когда админ меняет почту у юзера

2023-05-21 14:10 UTC, Pro100proff approved these changes

2023-05-21 14:10 UTC, merged