feature/fmh_back77 Creating method getting list of users for admin in…
fmh-charity/fmh-backend pull request #252
Opened 2023-05-31 04:52 UTC by EvgeniySiganov

Создать метод получения списка пользователей для админа системы вместе с фильтром и пагинацией

https://pmhproject.myjetbrains.com/youtrack/articles/pmh-A-14/09-Upravlenie-polzovatelyami#2.5-poisk-v-spiske-polzovatelej

Модель данных
https://pmhproject.myjetbrains.com/youtrack/articles/pmh-A-14/09-Upravlenie-polzovatelyami#3.1-ekrannaya-forma-spiska-zaregistrirovannyh-polzovatelej

‌

Создать JPASpecification для сущности User

[Use Criteria Queries in a Spring Data Application | Baeldung](https://www.baeldung.com/spring-data-criteria-queries#specifications)

создать фильтры на следующие поля : user.profile.firstname, user.profile.lastname, user.profile.middlename, user.profile.email, [user.userRoles.id](http://user.userroles.id/), user.userRoleClaim.Status

‌
Создать эндпойнт получения списка пользователей GET /users

Метод на вход получает следующие параметры: text:String, roleIds:List<Int>, confirmed : Boolean, пагинация

все параметры , кроме пагинации могут быть пустыми

метод доступен только админу

на выход отдается List<ru.iteco.fmh.dto.user.UserShortInfoDto>

Создать сервисный метод получения списка пользователей:

Создаем объект Criteria
Проходимся по всем параметрам и добавляем фильтры для непустых полей
Отправляем запрос userRepository.findAll(criteria, pageable)
Возвращаем ответ в виде List<ru.iteco.fmh.dto.user.UserShortInfoDto>

2023-06-08 17:42 UTC, Pro100proff requested changes

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/controller/UsersController.java
> +            @Parameter(name = "confirmed", description = "Cтатус подтверждения пользователя")
описание лучше сделать "показывать только подтвержденных пользователей"

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        Specification<User> createSpecification = (root, query, criteriaBuilder) -> {
надо вынести в отдельный метод createQuery

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("firstName")), "%" + text.toLowerCase() + "%"),
точно ли нужно приводить к lowerCase? Если имя Иван например поиск будет идти просто по иван в нижнем регистре?

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                    predicates.add(criteriaBuilder.or(root.join("userRoleClaim", JoinType.LEFT).isNull(),
проверь для пользователей у которых нет записи в userRoleClaim

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
очень странная конструкция. Зачем  predicates создаем вместо прямого использования везде criteriaBuilder ?

2023-06-08 17:42 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                .distinct()
есть дубли?

2023-06-09 04:47 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/controller/UsersController.java
> +            @Parameter(name = "confirmed", description = "Cтатус подтверждения пользователя")
поправил

2023-06-09 04:47 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +        Specification<User> createSpecification = (root, query, criteriaBuilder) -> {
вынес

2023-06-09 04:49 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("firstName")), "%" + text.toLowerCase() + "%"),
проверил, без приведения к общему регистру не ищет "николай", хотя в бд есть "Николай"

2023-06-09 04:58 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                    predicates.add(criteriaBuilder.or(root.join("userRoleClaim", JoinType.LEFT).isNull(),
<img width="450" alt="Screenshot 2023-06-09 at 12 51 06" src="https://github.com/fmh-charity/fmh-backend/assets/68127765/826aa7f6-6a15-4029-8b38-0f2e4b7be6b2">
 в бд только две записи userRoleClime (не подтверждённая у userId = 3), ниже ответ с на запрос confirmed = true:
`[
  {
    "id": 4,
    "firstName": "Алия",
    "lastName": "Цветкова",
    "middleName": "Валерьяновна",
    "roles": [
      "ROLE_MEDICAL_WORKER"
    ],
    "email": {
      "name": "login4@gmail.com",
      "confirmed": false
    },
    "isConfirmed": true,
    "admin": false
  },
  {
    "id": 2,
    "firstName": "Данил",
    "lastName": "Лебедев",
    "middleName": "Александрович",
    "roles": [
      "ROLE_ADMINISTRATOR"
    ],
    "email": {
      "name": "login2@gmail.com",
      "confirmed": false
    },
    "isConfirmed": true,
    "admin": true
  },
  {
    "id": 5,
    "firstName": "Зоя",
    "lastName": "Прохорова",
    "middleName": "Альфредовна",
    "roles": [
      "ROLE_ADMINISTRATOR"
    ],
    "email": {
      "name": "login5@gmail.com",
      "confirmed": false
    },
    "isConfirmed": true,
    "admin": true
  },
  {
    "id": 1,
    "firstName": "Николай",
    "lastName": "Смирнов",
    "middleName": "Петрович",
    "roles": [
      "ROLE_MEDICAL_WORKER",
      "ROLE_ADMINISTRATOR"
    ],
    "email": {
      "name": "login1@gmail.com",
      "confirmed": false
    },
    "isConfirmed": true,
    "admin": true
  }
]`

2023-06-11 07:13 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                .distinct()
да

2023-06-11 08:54 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
Создаю что-бы можно было добавлять сразу несколько придикатов и искать уже по их множеству.
А ты как предлагаешь вот так? ->
`private Specification<User> createQueryByOnePredicate(String text, List<Integer> roleIds, Boolean isConfirmed) {
        return (root, query, criteriaBuilder) -> {

            if (text != null && !text.isEmpty()) {
                return criteriaBuilder.or(
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("firstName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("lastName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("middleName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("email")), "%" + text.toLowerCase() + "%")
                );
            }
            if (roleIds != null && !roleIds.isEmpty()) {
                return root.join("userRoles").get("id").in(roleIds);
            }
            if (isConfirmed != null) {
                if (isConfirmed) {
                    return criteriaBuilder.or(root.join("userRoleClaim", JoinType.LEFT).isNull(),
                            criteriaBuilder.equal(root.get("userRoleClaim").get("status"), CONFIRMED));
                } else {
                    return criteriaBuilder.notEqual(root.get("userRoleClaim").get("status"), CONFIRMED);
                }
            }

            return null;
        };
    }`

так ищет, но по первому заполненному переданному параметру

2023-07-05 18:07 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                .distinct()
не должно быть. Надо запрос проверить

2023-07-05 18:07 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
предлагаю не return делать а просто использовать criteriaBuilder как накопитель
criteriaBuilder.or(
                    criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("firstName")), "%" + text.toLowerCase() + "%"),
                    criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("lastName")), "%" + text.toLowerCase() + "%"),
                    criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("middleName")), "%" + text.toLowerCase() + "%"),
                    criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("email")), "%" + text.toLowerCase() + "%")
            );

потом 
criteriaBuilder.or(root.join("userRoleClaim", JoinType.LEFT).isNull(),
                        criteriaBuilder.equal(root.get("userRoleClaim").get("status"), CONFIRMED));
и т.д.
Мне непонятно почему мы через предикат накапливали фильтр

2023-07-08 07:31 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
`return (root, query, criteriaBuilder) -> {

            if (text != null && !text.isEmpty()) {
                criteriaBuilder.or(
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("firstName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("lastName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("middleName")), "%" + text.toLowerCase() + "%"),
                        criteriaBuilder.like(criteriaBuilder.lower(root.get("profile").get("email")), "%" + text.toLowerCase() + "%")
                );
            }
            if (roleIds != null && !roleIds.isEmpty()) {
                criteriaBuilder.or(root.join("userRoles").get("id").in(roleIds));
            }
            if (isConfirmed != null) {
                if (isConfirmed) {
                    criteriaBuilder.or(root.join("userRoleClaim", JoinType.LEFT).isNull(),
                            criteriaBuilder.equal(root.get("userRoleClaim").get("status"), CONFIRMED));
                } else {
                    criteriaBuilder.notEqual(root.get("userRoleClaim").get("status"), CONFIRMED);
                }
            }

            return criteriaBuilder.......;
        };`

подскажи плиз, я в итоге должен в этом методе toPredicate возвратить объект Predicate после накопления критериев отбора. Не понимаю какую конструкцию в return использовать (criteriaBuilder...)

2023-07-24 17:07 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
посмотри здесь как через Filter реализовано https://habr.com/ru/sandbox/95575/
ожидаю что будут запросы реализовываться накопительно в объекте Filter, который потом отправится в запрос
Либо здесь посмотри как через спеки делается

2023-07-30 05:49 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
сделал через Фильтр

2023-07-30 10:30 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/user/UserServiceImpl.java
> +                .distinct()
там в вильтре в методе
`private Predicate buildContainsRoleIdsPredicate(Condition condition, Root root) {
        return root.join("userRoles").get("id").in((List<Integer>) condition.getValue());
    }`
в такой реализации если например будет несколько id в запросе (1, 2) и будут юзеры в бд у кого обе этой роли имеется то предикат будет содержать два одинаковый юзера.

2023-09-27 18:41 UTC, Pro100proff approved these changes

2023-09-28 08:28 UTC, merged