Fmh back81
fmh-charity/fmh-backend pull request #272
Opened 2023-07-25 14:50 UTC by pandamaroder

GET Employee by id 
pandamaroder

https://trello.com/c/MbATu2rl

2023-09-27 18:35 UTC, Pro100proff requested changes

2023-09-27 18:35 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Зачем такие правки модели? Fetchtype Lazy используем

2023-09-27 18:35 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @JoinColumn(name = "profile_id", referencedColumnName = "id")
для чего нужно referencedColumnName?

2023-09-27 18:35 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/EmployeeRepository.java
> +    Employee findEmployeeById(int id);
уже под капотом спринг создает метод findById для любой сущности, это лишнее

2023-09-27 18:35 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/employee/EmployeeServiceImpl.java
> +        Optional<Employee> employeeFindById = employeeRepository.findById(id);
название переменной достаточно просто employee

2023-09-27 18:35 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +@ToString
зачем?

2023-09-30 12:21 UTC, pandamaroder commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Исходя из паттерна использования модели employee - поле Profile используется при каждом обращении к этой модели, поэтому используем Eager, однако если существует перспектива использования этого поля другим образом, можно вернуть на Lazy

2023-09-30 14:03 UTC, pandamaroder commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @JoinColumn(name = "profile_id", referencedColumnName = "id")
Из джава доков : 
Default (only applies if single join column is being used): The same name as the primary key column of the referenced table.
Значит, непосредственно указывать этот параметр по аннотации не требуется в данном случае, и зависит от договоренностей в команде -> соответственно, указала по аналогии с @Entity  User

2023-09-30 14:04 UTC, pandamaroder commented on backend/src/main/java/ru/iteco/fmh/dao/repository/EmployeeRepository.java
> +    Employee findEmployeeById(int id);
@Pro100proff удалила

2023-09-30 14:04 UTC, pandamaroder commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +@ToString
@Pro100proff  исправлено

2023-09-30 14:27 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Eager делаем в случае исключения(если падаем по производительности например)
Сейчас оставляем только Lazy

2023-09-30 14:30 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @JoinColumn(name = "profile_id", referencedColumnName = "id")
да это лишнее

2023-09-30 14:38 UTC, pandamaroder commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @JoinColumn(name = "profile_id", referencedColumnName = "id")
@Pro100proff  для User тоже удалить?

2023-09-30 14:58 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/employee/Employee.java
> +    @JoinColumn(name = "profile_id", referencedColumnName = "id")
только здесь

2023-09-30 16:02 UTC, Pro100proff approved these changes

2023-09-30 16:02 UTC, merged