feature/fmh_back96 Исправить контроллер получения пациентов
fmh-charity/fmh-backend pull request #275
Opened 2023-09-23 16:50 UTC by 0202-D

https://trello.com/c/frhmbBBz/96-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%B0%D1%86%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2

2023-09-26 15:01 UTC, Pro100proff requested changes

2023-09-26 15:01 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/Room.java
> +    @JsonIgnore
зачем?

2023-09-26 15:28 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/controller/PatientsController.java
> +            @Parameter(name = "pages", description = "От 0")
Да, сортировка не срабатывала и выглядело в swagger менее понятно, особо не стал углубляться, посчитав это не принципиальным, могу доработать, если нужно

2023-09-27 18:25 UTC, Pro100proff requested changes

2023-09-27 18:25 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/model/Room.java
> +    @JsonIgnore
У нас nurseStation перестанет сохраняться, если мы заигнорим при сериализации

2023-09-28 04:25 UTC, 0202-D commented on backend/src/main/java/ru/iteco/fmh/model/Room.java
> +    @JsonIgnore
Поправил,, поставил transactional,проверил, все работает

2023-09-29 15:32 UTC, Pro100proff approved these changes

2023-09-29 15:32 UTC, merged