Fmh back97
fmh-charity/fmh-backend pull request #286
Opened 2023-10-30 02:13 UTC by EvgeniySiganov

Изменить
По аналогии с Исправить контроллер получения пациентов
ГОТОВО
 необходимо изменить контроллер ru.iteco.fmh.controller.WishesController#getWishes

Метод принимает просто строку которая будет служить для поиска по столбцам ФИО пациента, статус, исполнитель

Сортировка должна быть по тем же полям

UPD: в текущем коммите осуществляется сортировка только по id, status

2023-10-30 18:04 UTC, Pro100proff requested changes

2023-10-30 18:04 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/dao/repository/WishRepository.java
> +            """
Поменяй плиз запрос на такой 
select distinct w.*
from wish w
         join wish_visibility wv on w.id = wv.wish_id
         join roles r on wv.role_id = r.id
         left join wish_executors we on w.id = we.wish_id
         left join users u on u.id = we.executor_id
         left join profile p on u.profile_id = p.id
         left join patient pt on pt.id = w.patient_id
         left join profile pr on pr.id = pt.profile_id
         left join users uc on uc.id = w.creator_id
where w.deleted = false
  and (r.name in :roleNames or uc.login = :creatorLogin)
  and (w.status like '%Боба%'
    or lower(p.first_name) like lower('%Боба%')
    or lower(p.last_name) like lower('%Боба%')
    or lower(p.middle_name) like lower('%Боба%')
    or lower(pr.first_name) like lower('%Боба%')
    or lower(pr.last_name) like lower('%Боба%')
    or lower(pr.middle_name) like lower('%Боба%')
    )

2023-10-30 18:04 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishService.java
> +    List<WishDto> getWishes(PageRequest pageRequest, String searchValue);
вернуть WishPaginationDto

2023-10-30 18:04 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishServiceImpl.java
> +    public List<WishDto> getWishes(PageRequest pageRequest, String searchValue) {
здесь еще нужно было добавить значение , что если searchValue пусто, то искать просто всех с пагинацией

2023-11-01 03:14 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/wish/WishDtoToWishConverter.java
> +    private final WishExecutorsRepository wishExecutorsRepository;
закомментил эти переменные, не нашёл в WishServiceImpl конвертации из WishDto в Wish. Не понятно зачем он

2023-11-01 04:53 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/controller/WishesController.java
> +    public List<WishDto> getWishes(
оставил

2023-11-01 04:53 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/controller/WishesController.java
> +        List<WishDto> wishDtos = wishService.getWishes(PageRequest.of(pages, elements, sort), searchValue);
убрал, дебажил так

2023-11-01 04:54 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/dao/repository/WishRepository.java
> +            """
Поменял, но в плане проблемы с сортировкой ничего не поменялось

2023-11-01 04:55 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishService.java
> +    List<WishDto> getWishes(PageRequest pageRequest, String searchValue);
вернул

2023-11-01 05:24 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishServiceImpl.java
> +    public List<WishDto> getWishes(PageRequest pageRequest, String searchValue) {
сделал запрос так чтобы попадало всё что deleted = false и в зоне видимости пользователя (роли или логин создателя) в этом случае

2023-11-01 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/converter/wish/WishDtoToWishConverter.java
> +    private final WishExecutorsRepository wishExecutorsRepository;
тогда просто не трогай его, или удали полностью. Закомменченный код не нужно оставлять

2023-11-01 17:22 UTC, Pro100proff commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishServiceImpl.java
> +    public List<WishDto> getWishes(PageRequest pageRequest, String searchValue) {
если строка пустая придет , мы все значения получим?

2023-11-02 02:55 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/converter/wish/WishDtoToWishConverter.java
> +    private final WishExecutorsRepository wishExecutorsRepository;
Удалил

2023-11-02 03:04 UTC, EvgeniySiganov commented on backend/src/main/java/ru/iteco/fmh/service/wish/WishServiceImpl.java
> +    public List<WishDto> getWishes(PageRequest pageRequest, String searchValue) {
Да, исключая:
1) маркированные как удалённые
2) неразрешённые для просмотра текущим пользователем
вот что приходит админу + мед работнику:
{
  "pages": 0,
  "elements": [
    {
      "id": 1,
      "patient": {
        "id": 1,
        "firstName": "PatientOnefirstname",
        "middleName": "PatientOnemiddlename",
        "lastName": "PatientOnelastname"
      },
      "title": "wish-title1",
      "description": "wish1-description",
      "creator": {
        "id": 1,
        "firstName": "Николай",
        "middleName": "Петрович",
        "lastName": "Смирнов"
      },
      "createDate": 1698822133940,
      "planExecuteDate": 1698822133940,
      "factExecuteDate": null,
      "status": "OPEN",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1,
        2
      ],
      "wishExecutors": [
        {
          "executor": {
            "id": 1,
            "firstName": "Николай",
            "middleName": "Петрович",
            "lastName": "Смирнов"
          },
          "joinDate": 1698822134068,
          "finishDate": 1698908534068
        }
      ],
      "wishPriority": "RED",
      "helpRequest": false
    },
    {
      "id": 2,
      "patient": {
        "id": 2,
        "firstName": "PatientTwofirstname",
        "middleName": "PatientTwomiddlename",
        "lastName": "PatientTwolastname"
      },
      "title": "wish-title2",
      "description": "wish2-description",
      "creator": {
        "id": 2,
        "firstName": "Данил",
        "middleName": "Александрович",
        "lastName": "Лебедев"
      },
      "createDate": 1698735733940,
      "planExecuteDate": 1699254133940,
      "factExecuteDate": null,
      "status": "IN_PROGRESS",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1,
        2
      ],
      "wishExecutors": [
        {
          "executor": {
            "id": 2,
            "firstName": "Данил",
            "middleName": "Александрович",
            "lastName": "Лебедев"
          },
          "joinDate": 1698822134068,
          "finishDate": 1698908534068
        },
        {
          "executor": {
            "id": 1,
            "firstName": "Николай",
            "middleName": "Петрович",
            "lastName": "Смирнов"
          },
          "joinDate": 1698822134068,
          "finishDate": 1698908534068
        }
      ],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 3,
      "patient": {
        "id": 3,
        "firstName": "PatientThreefirstname",
        "middleName": "PatientThreemiddlename",
        "lastName": "PatientThreelastname"
      },
      "title": "wish-title3",
      "description": "wish3-description",
      "creator": {
        "id": 3,
        "firstName": "Егор",
        "middleName": "Богданович",
        "lastName": "Горбунов"
      },
      "createDate": 1698649333940,
      "planExecuteDate": 1699167733940,
      "factExecuteDate": null,
      "status": "CANCELLED",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1
      ],
      "wishExecutors": [],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 4,
      "patient": {
        "id": 1,
        "firstName": "PatientOnefirstname",
        "middleName": "PatientOnemiddlename",
        "lastName": "PatientOnelastname"
      },
      "title": "wish-title4",
      "description": "wish4-description",
      "creator": {
        "id": 4,
        "firstName": "Алия",
        "middleName": "Валерьяновна",
        "lastName": "Цветкова"
      },
      "createDate": 1698562933940,
      "planExecuteDate": 1699081333940,
      "factExecuteDate": 1698822133940,
      "status": "EXECUTED",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1
      ],
      "wishExecutors": [],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 5,
      "patient": {
        "id": 5,
        "firstName": "PatientFivefirstname",
        "middleName": "PatientFivemiddlename",
        "lastName": "PatientFivelastname"
      },
      "title": "wish-title5",
      "description": "wish5-description",
      "creator": {
        "id": 5,
        "firstName": "ИзменённоеИмяПять",
        "middleName": "ИзменённоеОтчествоПять",
        "lastName": "ИзменённаяФамилияПять"
      },
      "createDate": 1698476533940,
      "planExecuteDate": 1698994933940,
      "factExecuteDate": null,
      "status": "IN_PROGRESS",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1
      ],
      "wishExecutors": [
        {
          "executor": {
            "id": 3,
            "firstName": "Егор",
            "middleName": "Богданович",
            "lastName": "Горбунов"
          },
          "joinDate": 1698822134068,
          "finishDate": 1698908534068
        }
      ],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 6,
      "patient": {
        "id": 1,
        "firstName": "PatientOnefirstname",
        "middleName": "PatientOnemiddlename",
        "lastName": "PatientOnelastname"
      },
      "title": "wish-title6",
      "description": "wish6-description",
      "creator": {
        "id": 5,
        "firstName": "ИзменённоеИмяПять",
        "middleName": "ИзменённоеОтчествоПять",
        "lastName": "ИзменённаяФамилияПять"
      },
      "createDate": 1698217333940,
      "planExecuteDate": 1698908533940,
      "factExecuteDate": null,
      "status": "OPEN",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        1,
        2
      ],
      "wishExecutors": [],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 7,
      "patient": {
        "id": 1,
        "firstName": "PatientOnefirstname",
        "middleName": "PatientOnemiddlename",
        "lastName": "PatientOnelastname"
      },
      "title": "wish-title7",
      "description": "wish7-description",
      "creator": {
        "id": 5,
        "firstName": "ИзменённоеИмяПять",
        "middleName": "ИзменённоеОтчествоПять",
        "lastName": "ИзменённаяФамилияПять"
      },
      "createDate": 1698044533940,
      "planExecuteDate": 1698908533940,
      "factExecuteDate": null,
      "status": "OPEN",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": "room1-comment"
      },
      "wishVisibility": [
        2
      ],
      "wishExecutors": [],
      "wishPriority": "YELLOW",
      "helpRequest": false
    },
    {
      "id": 8,
      "patient": {
        "id": 1,
        "firstName": "PatientOnefirstname",
        "middleName": "PatientOnemiddlename",
        "lastName": "PatientOnelastname"
      },
      "title": "wish-title8",
      "description": "wish8-description",
      "creator": {
        "id": 5,
        "firstName": "ИзменённоеИмяПять",
        "middleName": "ИзменённоеОтчествоПять",
        "lastName": "ИзменённаяФамилияПять"
      },
      "createDate": 1698130933940,
      "planExecuteDate": 1698908533940,
      "factExecuteDate": null,
      "status": "OPEN",
      "room": {
        "id": 1,
        "name": "room1",
        "nurseStationId": 1,
        "maxOccupancy": 10,
        "comment": [...]

2023-11-07 16:29 UTC, merged